SET sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

-- All NBA Stats

SELECT *
FROM nbaplayoffs.nbastats;

-- Not important but I tried attempting a partition

SELECT FULLNAME, MAX(YEARS) OVER (PARTITION BY PPG) AS MOST_YEAR
FROM nbaplayoffs.nbastats;

-- PLAYERS THAT AVERAGE MORE THAN 12 REBOUNDS A GAME

SELECT FULLNAME, RPG, MPG
FROM nbaplayoffs.nbastats
WHERE RPG > 12;

--PLAYERS THAT AVERAGE MORE THAN 28 POINTS A GAME

SELECT FULLNAME, PPG
FROM nbaplayoffs.nbastats
WHERE PPG > 28;

--PLAYERS THAT AVERAGE MORE THAN 10 ASSIST A GAME
SELECT FULLNAME, APG
FROM nbaplayoffs.nbastats
WHERE APG > 10;

--WHICH PLAYER AVERAGE MOST POINTS FOR EACH POSITION
SELECT MAX(PPG), POS
FROM nbaplayoffs.nbastats
GROUP BY POS

--PLAYER AVERAGES MOST REBOUNDS BY POSITION
SELECT FULLNAME, MAX(RPG), POS
FROM nbaplayoffs.nbastats
GROUP BY FULLNAME, POS;

--players that average 90% with at least 20 attempts
SELECT FULLNAME, `FT%`
FROM nbaplayoffs.nbastats
WHERE `FT%` >= 0.9 AND FTA > 20;

--PLAYERS THAT AVERAGE MORE THAN 2 STEALS A GAME
SELECT FULLNAME, SPG
FROM nbaplayoffs.nbastats
WHERE SPG > 2;


--PLAYERS THAT AVERAGE MORE THAN 2 BLOCKS PER GAME
SELECT FULLNAME, BPG
FROM nbaplayoffs.nbastats
WHERE BPG > 2;

--PLAYER THAT AVERAGE THE MOST POINTS PER GAME
SELECT FULLNAME, PPG
FROM nbaplayoffs.nbastats
WHERE PPG = (SELECT MAX(PPG)
FROM nbaplayoffs.nbastats);

--PLAYERS THAT AVERAGE THE MOST POINTS WITH AT LEAST 10 ASSISTS
SELECT FULLNAME, PPG
FROM nbaplayoffs.nbastats
WHERE PPG = (SELECT MAX(PPG)
FROM nbaplayoffs.nbastats
WHERE APG > 10);

--top 10 players that average the most points per gamr
SELECT FULLNAME, PPG
FROM nbaplayoffs.nbastats
ORDER BY PPG DESC
LIMIT 10;

--TOP 10 PLAYERS THAT AVERAGE THE MOST REBOUNDS PER GAME
SELECT FULLNAME, RPG
FROM nbaplayoffs.nbastats
ORDER BY RPG DESC
LIMIT 10;

--TOP 10 PLAYERS THAT AVERAGE THE MOST STEALS PER GAME
SELECT FULLNAME, SPG
FROM nbaplayoffs.nbastats
ORDER BY SPG DESC
LIMIT 10;

--TOP 10 PLAYERS THAT AVERAGE THE MOST ASSIST PER GAME
SELECT FULLNAME, APG
FROM nbaplayoffs.nbastats
ORDER BY APG DESC
LIMIT 10;

--PLAYERS THAT AVERAGE THE MOST POINTS BY AGE 
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 19
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 20
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 21
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 22
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 23
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 24
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 25
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 26
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 27
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 28
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 29
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 30
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 31
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 32
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 33
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 34
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 35
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 36
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 37
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 38
ORDER BY PPG DESC
LIMIT 1)
