SET sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

SELECT *
FROM nbaplayoffs.nbastats;

SELECT FULLNAME, MAX(YEARS) OVER (PARTITION BY PPG) AS MOST_YEAR
FROM nbaplayoffs.nbastats;

SELECT YEARS, MAX(PPG), FULLNAME
FROM nbaplayoffs.nbastats
GROUP BY YEARS
ORDER BY YEARS;

SELECT FULLNAME, RPG, MPG
FROM nbaplayoffs.nbastats
WHERE RPG > 12;

SELECT FULLNAME, PPG
FROM nbaplayoffs.nbastats
WHERE PPG > 28;

SELECT FULLNAME, APG
FROM nbaplayoffs.nbastats
WHERE APG > 10;

SELECT MAX(PPG), POS
FROM nbaplayoffs.nbastats
GROUP BY POS

SELECT FULLNAME, MAX(RPG), POS
FROM nbaplayoffs.nbastats
GROUP BY FULLNAME, POS;

SELECT FULLNAME, `FT%`
FROM nbaplayoffs.nbastats
WHERE `FT%` >= 0.9 AND FTA > 20;

SELECT FULLNAME, SPG
FROM nbaplayoffs.nbastats
WHERE SPG > 2;

SELECT FULLNAME, BPG
FROM nbaplayoffs.nbastats
WHERE BPG > 2;

SELECT FULLNAME, PPG
FROM nbaplayoffs.nbastats
WHERE PPG = (SELECT MAX(PPG)
FROM nbaplayoffs.nbastats);

SELECT FULLNAME, PPG
FROM nbaplayoffs.nbastats
WHERE PPG = (SELECT MAX(PPG)
FROM nbaplayoffs.nbastats
WHERE APG > 10);

SELECT FULLNAME, PPG
FROM nbaplayoffs.nbastats
ORDER BY PPG DESC
LIMIT 10;

SELECT FULLNAME, RPG
FROM nbaplayoffs.nbastats
ORDER BY RPG DESC
LIMIT 10;

SELECT FULLNAME, SPG
FROM nbaplayoffs.nbastats
ORDER BY SPG DESC
LIMIT 10;

SELECT FULLNAME, APG
FROM nbaplayoffs.nbastats
ORDER BY APG DESC
LIMIT 10;

(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 19
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 20
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 21
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 22
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 23
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 24
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 25
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 26
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 27
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 28
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 29
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 30
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 31
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 32
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 33
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 34
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 35
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 36
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 37
ORDER BY PPG DESC
LIMIT 1)
UNION
(SELECT FULLNAME, PPG, YEARS
FROM nbaplayoffs.nbastats
WHERE YEARS = 38
ORDER BY PPG DESC
LIMIT 1)
